# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85f83f0a1583bf552d374a023735f379212c79b091a2e98acd9f7712fffeabdaa80023031ad12d59d213243660d6638334d98f8447febc7ee4df4ef15eb224b

test:
  secret_key_base: 5562f608a49f9a5666b2510f39b83a53200e5e3e1b7c0060ea61c44c146932240071ce99d3d69682c4b92673ab72224992912d5ca5ce55f54a90bcacf5f3200a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
